---
title: 'HW: create an R package'
author: "csiu"
date: "November 19, 2015"
output: html_document
---

----

In this [homework-assignment](http://stat545-ubc.github.io/hw10_package.html), we made an R package  called [`foofactors`](https://github.com/csiu/foofactor).

----

## Homework checklist + comments

**What we have already done**

- [x] Set up the directory structure for a package using `devtools::create()`
- [x] put it under version control with `use_git()`
- [x] define functions, such as `fbind()` and `freq_out()`, in the scripts `R/fbind.R` and `R/freq_out.R`, respectively
- [x] use `load_all()` to quickly simulate package build + install
- [x] use `check()` to run R CMD check
- [x] use “Build & Reload” to properly build and install the package
- [x] edit the `DESCRIPTION` file of package metadata
- [x] specify a `LICENSE`
- [x] document and export the functions `fbind()` and `freq_out()` via roxygen2 comments
- [x] create documentation and manage the `NAMESPACE` file via document()
- [x] use `testthat` to implement unit testing
- [x] use a function from another package via `use_package()` and syntax like `otherpkg::foofunction()`
- [x] connect your local Git repo to a new remote on GitHub via `use_github()`
- [x] create a `README.md` that comes from rendering README.Rmd containing actual usage, via use_readme()
- [x] create a vignette via `use_vignette()` and build it via `build_vignettes()`

**The mission**

- [x] Define and export at least one new function, i.e. make it available to a user. We’d prefer more than one. Feel free to improve (or delete) the functions we already have.
    - added `should_factor_stay_factor()`
    - improved `fbind()` to include sorting of the factor levels
    - improved `freq_out()` to include sorting by frequency column
- [x] Give function arguments sensible defaults, where relevant.
    - `fbind(... level.as.appears = TRUE)` 
    - `freq_out(... n.sort = NULL)`
- [x] Use assertions to add some validity checks of function input.
    - made unit test to test that the input of `should_factor_stay_factor()` should be factor
- [x] Document all exported functions.
    - yes
- [x] Include at least three unit tests for every function that is exported.
    - `fbind()`
        1. will binds factors correctly
        2. levels are ordered as they appear
        3. will result to NA if input is not factor
    - `freq_out()`
        1. will creates a frequency table correctly
        2. sorting (e.g. by ascending/descending/null) of the frequency table is correct 
        3. will give a warning if the user specifies a sorting option not on the list 
    - `should_factor_stay_factor()`
        1. will return TRUE if # unique values != length
        2. will return FALSE if # unique values == lenght
        3. the input is a factor
- [x] There should be at least one expectation for success and one for failure.
    - yes
- [x] Your package should pass `check()` without errors (warnings and notes are OK, though it would be great if there were none).
    - success is glorious!!
- [ ] Keep updating the `README` and vignette to show usage of all the functions in the package. Your peer reviwer and TA will only have the README and vignette to go on when they try to use your package. Show them exactly what they can do! Remove boilerplate content from the vignette.
    - README is descriptive enough ;)
- [x] Push your package to GitHub, preferably a public repo. If you are uncomfortable with that, please contact Jenny and we’ll work around that. 
    - [foofactor](https://github.com/csiu/foofactor) is public ... if only I had private repos ... 
- [] Write your reflections in a document in your normal STAT 545 course repo and open the usual issue there. Make sure to provide a link to your package, so TAs/prof/peers can find it for review!

## Reflection/stream of concious thought

`devtools` made developing an R package easy. Is it "an R package" or "a R package"? I remember we use to use `roxygen` to do documentation ... now this is nicely wrapped up with `devtools::document()`. In my packge I included example data. You can do this by `devtools::use_data(robj)` to save the example data to `data/robj.rda` -- it is awesome. 

